FROM node:10

# Setting working directory. All the path will be relative to WORKDIR
WORKDIR /usr/src/app

# Installing dependencies
COPY package*.json ./
RUN npm install

# Copying source files
COPY . .
COPY .env.development .env

#Copying the robot.txt file
COPY  public/dev-robots.txt public/robots.txt
# Building app
RUN npm run build

EXPOSE 3000

# Running the app
CMD [ "npm", "start" ]


