apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-deployment
  namespace: b2c
  labels:
    app: blog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog
  template:
    metadata:
      labels:
        app: blog
    spec:
      containers:
      - name: blog
        image: 094697208586.dkr.ecr.ap-southeast-1.amazonaws.com/st-stg-blog:${BITBUCKET_BUILD_NUMBER}
        ports:
        - containerPort: 3000
        env:
          - name: NEXT_PUBLIC_this_site_url
            value: https://stg-blog.sharetrip.net
          - name: NEXT_PUBLIC_apiBaseUrl
            value: https://stg-api.sharetrip.net/api/
          - name: NEXT_PUBLIC_siteBaseUrl
            value: https://stg.sharetrip.net
          - name: NEXT_PUBLIC_hotelListSocketUrl
            value: https://stg-socket.sharetrip.net/hotel

---
kind: Service
apiVersion: v1
metadata:
  name: blog-service
  namespace: b2c
spec:
  type: NodePort
  selector:
    app: blog
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000

---
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta1
metadata:
  name: blog
  namespace: b2c
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: blog-deployment
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 60

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: blog-ingress
  namespace: b2c
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: stg-blog.sharetrip.net
    http:
      paths:
      - backend:
          serviceName: blog-service
          servicePort: 80
        path: /      